//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Home {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class About {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal About() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Home.About", typeof(About).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABOUT ME.
        /// </summary>
        public static string Box_Head {
            get {
                return ResourceManager.GetString("Box_Head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
        ///Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Box_Head_content {
            get {
                return ResourceManager.GetString("Box_Head_content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt incididunt ut labore et dolore magna aliqua1.
        /// </summary>
        public static string box_left1_content {
            get {
                return ResourceManager.GetString("box_left1_content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WEB DESIGN.
        /// </summary>
        public static string box_left1_title {
            get {
                return ResourceManager.GetString("box_left1_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt incididunt ut labore et dolore magna aliqua2.
        /// </summary>
        public static string box_left2_content {
            get {
                return ResourceManager.GetString("box_left2_content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ONLINE MARKETTING.
        /// </summary>
        public static string box_left2_title {
            get {
                return ResourceManager.GetString("box_left2_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt incididunt ut labore et dolore magna aliqua3.
        /// </summary>
        public static string box_right1_content {
            get {
                return ResourceManager.GetString("box_right1_content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GRAPHIC DESIGN.
        /// </summary>
        public static string box_right1_title {
            get {
                return ResourceManager.GetString("box_right1_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt incididunt ut labore et dolore magna aliqua4.
        /// </summary>
        public static string box_right2_content {
            get {
                return ResourceManager.GetString("box_right2_content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEO.
        /// </summary>
        public static string box_right2_title {
            get {
                return ResourceManager.GetString("box_right2_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua1..
        /// </summary>
        public static string Top_Box1_Content {
            get {
                return ResourceManager.GetString("Top_Box1_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VALUES.
        /// </summary>
        public static string Top_Box1_Title {
            get {
                return ResourceManager.GetString("Top_Box1_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua2..
        /// </summary>
        public static string Top_Box2_Content {
            get {
                return ResourceManager.GetString("Top_Box2_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GOALS.
        /// </summary>
        public static string Top_Box2_Title {
            get {
                return ResourceManager.GetString("Top_Box2_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua3..
        /// </summary>
        public static string Top_Box3_Content {
            get {
                return ResourceManager.GetString("Top_Box3_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HOBBIES.
        /// </summary>
        public static string Top_Box3_Title {
            get {
                return ResourceManager.GetString("Top_Box3_Title", resourceCulture);
            }
        }
    }
}
