//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Home {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Education {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Education() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Home.Education", typeof(Education).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo..
        /// </summary>
        public static string education1Content {
            get {
                return ResourceManager.GetString("education1Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.0 GPA.
        /// </summary>
        public static string education1Gpa {
            get {
                return ResourceManager.GetString("education1Gpa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reeves college   /   June 2006 May 2008.
        /// </summary>
        public static string education1Period {
            get {
                return ResourceManager.GetString("education1Period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CIT DEPLOMA.
        /// </summary>
        public static string education1Title {
            get {
                return ResourceManager.GetString("education1Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo..
        /// </summary>
        public static string education2Content {
            get {
                return ResourceManager.GetString("education2Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.0 GPA.
        /// </summary>
        public static string education2Gpa {
            get {
                return ResourceManager.GetString("education2Gpa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reeves college   /   June 2008 May 2010.
        /// </summary>
        public static string education2Period {
            get {
                return ResourceManager.GetString("education2Period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GRAPHIC DESIGN DEPLOMA.
        /// </summary>
        public static string education2Title {
            get {
                return ResourceManager.GetString("education2Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        public static string educationNr {
            get {
                return ResourceManager.GetString("educationNr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo..
        /// </summary>
        public static string educationP1 {
            get {
                return ResourceManager.GetString("educationP1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua..
        /// </summary>
        public static string educationP2 {
            get {
                return ResourceManager.GetString("educationP2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MY EDUCATION.
        /// </summary>
        public static string educationTitle {
            get {
                return ResourceManager.GetString("educationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo..
        /// </summary>
        public static string workExp1Content {
            get {
                return ResourceManager.GetString("workExp1Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lethbridge   /   June 2006 May 2008.
        /// </summary>
        public static string workExp1Period {
            get {
                return ResourceManager.GetString("workExp1Period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 years.
        /// </summary>
        public static string workExp1TimeInterval {
            get {
                return ResourceManager.GetString("workExp1TimeInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WEB DEVELOPER.
        /// </summary>
        public static string workExp1Title {
            get {
                return ResourceManager.GetString("workExp1Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo..
        /// </summary>
        public static string workExp2Content {
            get {
                return ResourceManager.GetString("workExp2Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XYZ Company   /   June 2008 May 2010.
        /// </summary>
        public static string workExp2Period {
            get {
                return ResourceManager.GetString("workExp2Period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 year 11 months.
        /// </summary>
        public static string workExp2TimeInterval {
            get {
                return ResourceManager.GetString("workExp2TimeInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JUNIOR DESIGNER.
        /// </summary>
        public static string workExp2Title {
            get {
                return ResourceManager.GetString("workExp2Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo..
        /// </summary>
        public static string workExp3Content {
            get {
                return ResourceManager.GetString("workExp3Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABC Company   /   June 2010 May 2012.
        /// </summary>
        public static string workExp3Period {
            get {
                return ResourceManager.GetString("workExp3Period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 years.
        /// </summary>
        public static string workExp3TimeInterval {
            get {
                return ResourceManager.GetString("workExp3TimeInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LEAD WEB DESIGNER.
        /// </summary>
        public static string workExp3Title {
            get {
                return ResourceManager.GetString("workExp3Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WORK EXPERIENCE.
        /// </summary>
        public static string workExperienceTitle {
            get {
                return ResourceManager.GetString("workExperienceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo..
        /// </summary>
        public static string workExpP1 {
            get {
                return ResourceManager.GetString("workExpP1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua..
        /// </summary>
        public static string workExpP2 {
            get {
                return ResourceManager.GetString("workExpP2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        public static string workNr {
            get {
                return ResourceManager.GetString("workNr", resourceCulture);
            }
        }
    }
}
