//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Home {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Skills {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Skills() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Home.Skills", typeof(Skills).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONTACT ME.
        /// </summary>
        public static string contactData {
            get {
                return ResourceManager.GetString("contactData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traits learned and discovered along and across my web stage presence can be loaded to a podium place but I fear there are only three places and thy will haggle between them.
        ///So here they are in random order: optimism, attention, practicality, energy (coffee/antimatter)..
        /// </summary>
        public static string content {
            get {
                return ResourceManager.GetString("content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTML / CSS.
        /// </summary>
        public static string skill1Name {
            get {
                return ResourceManager.GetString("skill1Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 75.
        /// </summary>
        public static string skill1Percent {
            get {
                return ResourceManager.GetString("skill1Percent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Javascript / JQuery.
        /// </summary>
        public static string skill2Name {
            get {
                return ResourceManager.GetString("skill2Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 85.
        /// </summary>
        public static string skill2Percent {
            get {
                return ResourceManager.GetString("skill2Percent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C#.
        /// </summary>
        public static string skill3Name {
            get {
                return ResourceManager.GetString("skill3Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 90.
        /// </summary>
        public static string skill3Percent {
            get {
                return ResourceManager.GetString("skill3Percent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Server.
        /// </summary>
        public static string skill4Name {
            get {
                return ResourceManager.GetString("skill4Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 85.
        /// </summary>
        public static string skill4Percent {
            get {
                return ResourceManager.GetString("skill4Percent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ORACLE PL/SQL.
        /// </summary>
        public static string skill5Name {
            get {
                return ResourceManager.GetString("skill5Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 80.
        /// </summary>
        public static string skill5Percent {
            get {
                return ResourceManager.GetString("skill5Percent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MY SKILLS.
        /// </summary>
        public static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
    }
}
