//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Slider {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Slider() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Slider", typeof(Slider).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WEB &amp; GRAPHIC DESIGNER.
        /// </summary>
        public static string slide1Large {
            get {
                return ResourceManager.GetString("slide1Large", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #.
        /// </summary>
        public static string slide1Link {
            get {
                return ResourceManager.GetString("slide1Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LEARN MORE.
        /// </summary>
        public static string slide1Small {
            get {
                return ResourceManager.GetString("slide1Small", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WEB DESIGNER.
        /// </summary>
        public static string slide2Large {
            get {
                return ResourceManager.GetString("slide2Large", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #.
        /// </summary>
        public static string slide2Link {
            get {
                return ResourceManager.GetString("slide2Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LEARN MORE.
        /// </summary>
        public static string slide2Small {
            get {
                return ResourceManager.GetString("slide2Small", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GRAPHIC DESIGNER.
        /// </summary>
        public static string slide3Large {
            get {
                return ResourceManager.GetString("slide3Large", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #.
        /// </summary>
        public static string slide3Link {
            get {
                return ResourceManager.GetString("slide3Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LEARN MORE.
        /// </summary>
        public static string slide3Small {
            get {
                return ResourceManager.GetString("slide3Small", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #.
        /// </summary>
        public static string slide4Link {
            get {
                return ResourceManager.GetString("slide4Link", resourceCulture);
            }
        }
    }
}
